# Providing Your Own Data    {#own}

## Overview      {#own-over}

Users may import their own data into the Shiny application and have the application run the HWP model and Monte Carlo simulation.  The following documentation is intended to assist with the construction and explanation of the input file.  Once the user has built their own input file, the file can be uploaded to the Shiny application or read by the stand-alone model.  In either scenario a QA check verifies that the data are correctly compiled.  Once this is done, the application can display the user’s data and the user can download tables of the output.  The stand-alone model can provide arrays and tables of the output.  

The data reside in a single workbook formatted as a MS Excel file with the .xlsx extension.  The Excel file has many tabs, described below.  Provided examples and templates may be modified by the user when they construct their own import file.  The examples and templates are located in the GitHub folder "HWP Data".    

There are many values that the user should consider altering based on regional available and historic mill data, dump and landfill decomposition information, etc.  At a minimum users can provide yearly values of total harvested billion board feet from their region, alter the rest of the worksheets to reflect their year values, and make use of all other available values from one of the examples or templates.     

## Creation of the input file      {#own-input}  
This explanation may work best if the user opens example files, such as CA_Inputs_HWP_Model.xlsx or Oregon_Inputs_HWP_Model.xlsx, and examines the files while reading the description of each worksheet.   

The worksheet HWP_MODEL_OPTIONS allows the user to customize the operation and output of the HWP model. The values in this worksheet affect the operation of the stand-alone model and/or the Shiny application.  Below are options that the user may adjust:  

* DATASET.NAME (string): This value only affects the Shiny application.  This name will appear as an option in the upper-left pulldown menu in the application.  Avoid using the names "California" or "Oregon".    

* QA_TEST (TRUE, FALSE) – This value only affects the stand-alone model.  The default is TRUE.  If TRUE, the stand-alone code will examine all worksheets except HWP_MODEL_OPTIONS.  See Section \@ref(own-qa) below.  If FALSE, the code will skip the quality assurance step and attempt to load the worksheets without examining them.  There is little system time needed to conduct the QA test.   

* OUTPUT_ARRAYS (TRUE, FALSE) – This value only affects the stand-alone model.  If users would like the code to produce the analysis arrays so that they can trouble-shoot model issues or verify calculations, cell B2 should be TRUE (default). Otherwise, FALSE.   There is a noticeable time  savings in code execution to set to FALSE.    

* OUTPUT_TABLES (TRUE, FALSE) – This value only affects the stand-alone model.  This option allows users to select whether the code produces output tables for the base HWP analysis.  Default = TRUE.  

* SHIFTYEAR (TRUE, FALSE) – Affects both the Shiny application and stand-alone model.  If the user wants tabular and figure outputs of emissions and pools reported as occurring the year after harvest, cell E2 should be TRUE.  If the user wants those outputs reported as occurring during the same year as harvest, select FALSE.  

* PIU.LOSS (Double, 0.00 to 1.00) – Affects both the Shiny application and stand-alone model.  The current estimated loss of carbon entering PIU through manufacturing is 0.08, or 8%.  Enter the default value of 0.08 unless you wish to alter the amount.  Cannot exceed 1.0 or fall below 0.  

* ARRAYLOC (Text) – This value only affects the stand-alone model.  The default value is "HWP_Stand_Alone_Files/Arrays/".  If you wish to save arrays to a different folder, change the folder location value.  If you are using Windows, be sure to use the forward slash "/" between folder levels and not the back slash.  

* TABLELOC (Text) – This value only affects the stand-alone model.  The default value is "HWP_Stand_Alone_Files/Tables/".  If you wish to save tables to a different folder, change the folder location value.  If you are using Windows, be sure to use the forward slash "/" between folder levels and not the back slash.  

* RUN.MC (TRUE, FALSE) – This value only affects the Shiny application.  If you would like to run the Monte Carlo simulation on your data set, ensure that this value is TRUE.  The main model code will run and then verify that this value is TRUE, at which time it will source the Monte Carlo R code and run it.  Note: running the Monte Carlo simulation is very time consuming.  Set this option to FALSE if you are running the stand-alone model and are not currently interested in the Monte Carlo output.    

* R (Numeric, between 0 to 1) – Affects both the Shiny application and stand-alone model.  This value is the target Pearson’s correlation coefficient that will be used to correlate triangular distribution values in the Monte Carlo.  For instance, if the worksheet MonteCarloDistrParameters has three accuracy values for Harvest, depending on the year of harvest, the value for R will determine how correlated the three random draws are that are used to adjust the Harvest values for each iteration.   The default is 0.5, as was used in @stockmann2012.  

* OPT.START.VALUE (Numeric, between 0 and 1) – Affects both the Shiny application and stand-alone model.  The MonteCarloDistrParameters states minimum and maximum 90% Confidence Intervals from which the Monte Carlo random variables are to be drawn.  However, when we transform random uniform values into values from a triangular distribution, we need to know the triangular distribution endpoints.  In the Monte Carlo code, the function "ab.boundaries.fcn" performs a search algorithm to find the triangular distribution end points given the confidence intervals provided in the MonteCarloDistrParameters worksheet.  The default start value for the algorithm is 0.5 and likely does not need to be altered for the Monte Carlo code to function adequately.  

* N.ITER (Integer, 1 or greater) – Affects both the Shiny application and stand-alone model.  This value determines the number of iterations the Monte Carlo performs.  In the Shiny application, the Monte Carlo Estimates selection "Monte Carlo convergence estimation" produces convergence plots that track estimates for the last year examined in the model.  The plot shows the values for the mean, standard error, and 95% and 5% Confidence Intervals given the iterations performed.  Of the four, the Mean is most informative.  If the line is stable for many iterations (we seem to obtain fairly stable results with 2000 iterations) then you likely have a sufficient number of iterations.  The more iterations, the slower the code will run.  Too few iterations will provide unreliable results.  The default value is currently 100 runs which is likely too few but is sufficient to verify that the process works.  1000 to 2000 might be a recommended number for obtaining reliable estimates and determining what the length of the burn-in period should be.  

* BURN.IN (Integer, 0 or greater) - This value only affects the Shiny application.  In the same figure mentioned in the previous N.ITER description, there is a vertical magenta line that signifies the burn-in period. Everything to the left of the line is discarded when results are plotted in the Shiny application.  The user should set the BURN.IN value to the number of iterations after which the Monte Carlo appears fairly stable, e.g., the estimate for the mean approximates a horizontal line.    

* MC.ARRAY.OUT (TRUE, FALSE) – This value only affects the stand-alone model.  If TRUE, the Monte Carlo code will generate the (large) Microsoft Excel workbook MC_All.xlsx that contains all MMTC values for each year and each iteration of the Monte Carlo code.  There is a separate tab for Emitted with Energy Capture (eec), Emitted Without Energy Capture (ewoec), Solid Waste Disposal Sites carbon (swdsC), and Products in Use (pu).  The default is TRUE; if it is FALSE the code will run a bit faster and the large (~10 MB?) file will not be produced.  The file is provided for model assessment purposes.    

The worksheet Harvest_BF contains annual harvest values in billion board feet (BBF).  The left column must contain the heading "Year" and have years listed in sequential order from least to greatest.  Ownership columns may follow, with a final column entitled "Total" that must equal the ownership values.  Users may omit all but the Year and Total columns.  Users may have ownership values appear at some point after the first year of total harvest values; however, leave the ownership cells prior to the first year of ownership values blank and not filled with zeros.  The QA check sums the values to determine if they equal the total value, so a series of zeros obviously will cause the QA check to fail.

The worksheet BFCF contains the BBF to hundred Cubic Feet (CCF) conversion factors based on time periods.  There are only three columns, Conversion, StartYear, and EndYear.  Ensure that the first Start Year begins with the minimum Harvest_BF Year and that conversion time periods do not overlap.  The Conversion column values are formatted as doubles and StartYear and EndYear values are integers.

The worksheet TimberProdRatios contain the timber product ratios, or TPR.  The first column must be TimberProductID.  The remainder of the columns are named after the sequential years of harvest data, from the earliest year to the final year.  All year-column values must sum to one.  Row values may change over time.

The worksheet PrimaryProdRatios contain the primary product ratios, or PPR.  The first column must be PrimaryProductID.  The remainder of the columns are named after the sequential years of harvest data, from the earliest year to the final year.  All year-column values must sum to the number of TPR rows.  Row values may change over time.

The worksheet EndUseRatios contains the end use ratios, or EUR.  The first column must be EndUseID.  The remainder of the columns are named after the sequential years of harvest data, from the earliest year to the final year.  All year-column values must sum to the number of PPR rows.  Row values may change over time.

The worksheet RatioCategories acts as a link between TPR, PPR, and EUR categories.  The first three column labels, TimberProductID, PrimaryProductID, and EndUseID, must have the same names as the respective first columns of the previous three worksheets described.  The fourth through sixth column names are TimberProduct, PrimaryProduct, and EndUseProduct, and contain text describing what the categories contain.  Note that EndUseProduct is a subcategory of PrimaryProduct, and PrimaryProduct is a subcategory of TimberProduct.  The R code ignores columns 4 through 6; they are there for assisting users in identifying row values.  

The worksheet CCF_MT_Conversion contains carbon CCF to metric tons (MT) conversion factors for individual primary products.  The first column title must be PrimaryProductID, and the second column CCFtoMTconv.  The first column values must be integers and include all primary product ratio categories.  

The worksheet EU_HalfLives contains half-life values (in years) for each of the end use categories.  The first column must be titled EndUseID, the second EU_HalfLife.  The values for EndUseID must be integers and include all end use ratio categories.  

The worksheet DiscardFates contains values that apportions discarded carbon to different discard categories: BWEC = Burned with Energy Capture, BWoEC = Burned Without Energy Capture, Recovered, Composted, Landfills, and Dumps.  Paper (defined by the code as primary products where the column EndUseProduct in the worksheet RatioCategories contains the word "pulp") and wood products are allowed to have different discard ratio values.  The first two columns must be named DiscardType and DiscardDestination.  The remainder of the column titles are the years, in order, from longest ago to most recent.  The sum of each year-column should be two (all wood and all paper values within a column should sum to one).  

The worksheet Discard_HalfLives provides half-life values in years for paper and wood in dumps (Dumps), recovered products (Recovered), and the decaying portion of landfills (Landfills_decay).  It also, possibly confusingly, includes values for the proportion of wood and paper that end up in the non-decaying portion of landfills (Landfills_fixed).  The columns must be labeled Type, Dumps, Landfills_fixed, Landfills_decay, and Recovered.  

The worksheet MonteCarloValues allows users to define how much "noise" to introduce into the HWP model for the Monte Carlo simulation and to specify aspects of the Monte Carlo that they would like to control.  The worksheet needs to be altered to conform to the user’s data structure for the Monte Carlo to run.  That is, if users have data from 1970 – 2018, they will need to change First_Year and Last_Year values for some of the rows.  Users can change First_Year, Last_Year, MinCI, MaxCI, and CI values. They may add or delete rows for Harvest, TimberProdRatios, and PrimaryProdRatios.  Each row of the worksheet represents a vector of random draws, with one random draw per iteration.  If our model had 100 iterations and this worksheet had 20 rows, the R script will obtain 2000 random uniform draws between zero and one, 100 random values per row.  (Please use more than 100 iterations for your final runs.)  The R script will change these values to triangular distributions with a peak at 1.0 (column Peak Value) and lower and upper confidence intervals as defined by the columns MinCI and MaxCI.  The resulting random numbers for a given parameter (row) will have values that are above or below 1.0.  In general, the parameter values associated with each of the parameters are multiplied by the random number for a single iteration.  If the random number is 0.86, the parameter value will be reduced to 86% of its original size.  Below we describe each of the columns and column values in this worksheet.  

* Parameter_ID: This column is included for the user’s information; the R script does not rely upon it.  Each of the parameters to be altered is listed here.  Some parameters (namely, those after Parameter ID number 13) may have more than one set of random numbers generated for it.  For instance, if we wish for Harvest values to be modeled as becoming more accurate through time, reflecting improvements in reporting and data collection, we may wish to indicate three periods of years with increasing estimate precision.  A series of random numbers will be drawn for each of the time periods, and then correlated (see above).  Within an iteration, this example would have three correlated random numbers that would be used for the three periods of years.  The parameter ID for Harvest would be the same number repeated three times (14, 14, 14).    
* Parameter_Name: The column name, "Parameter Name", is not used by the code.  However, the column values are names for specific parameters that are used by the code.  These must remain unchanged.  The names can be repeated as necessary (following on the example for Parameter ID, Parameter ID 14, 14, 14 would be associated with Parameter Name "Harvest", "Harvest", "Harvest").  Below are descriptions of which parameters and worksheets each relates to:  

    + CCFtoMTC: This name translates as "hundred cubic feet converted to metric tons carbon".  Each Monte Carlo iteration will alter the conversion values associated with the worksheet CCF_MT_Conversion.    
    
    + EndUse_HalfLives: Each Monte Carlo iteration’s random number for this parameter will adjust the end use half life values found in EU_halflives.   
    
    + EndUseRatios: This variable refers to the end use ratio values found in the worksheet EndUseRatios.  Each iteration of the Monte Carlo will use one random value to change the end use ratio values.  See the discussion of the "Sum-To-One Constraint" in Section \@ref(model-mc-samphwp) to understand how the values are altered.  
    + DiscardedDispositionRatios, Paper: There are two rows in the Parameter Name column with the name DiscardedDispositionsRatios.  The adjacent column, "Paper", indicates whether these disposition ratios are for paper (1) or wood (0). The disposition ratios are from the worksheet DiscardFates.  They determine what fraction of paper or wood enter the categories of Burned with Energy Capture, Burned Without Energy Capture, Recovered, Composted, Landfills, or Dumps.  Like End Use Ratios, these ratios are subject to the sum-to-one constraint.    
    
    + LandfillDecayLimits: The wood and paper values represent the landfill decay limits, or the proportion of landfill material that is subject to decay.  The values are obtained from the worksheet Discard_HalfLives.  
    
    + Landfill_HalfLives, Dump_HalfLives, Recovered_HalfLives: the six rows with these parameter names are associated with wood and paper decomposition half-lives for materials subject to decay in landfills, dumps, and in recovered products.  The values are obtained from the worksheet Discard_HalfLives.    
    
    + Harvest: This parameter references the cubic-foot volume amounts harvested each year.  The values are originally provided as board feet from the worksheet Harvest_BF, but they are transformed in the original (non-Monte Carlo) portion of the analysis and the transformed values are used in the Monte Carlo.  There may be more than one row labeled as Harvest, reflecting different accuracies to be used for different year-ranges.    
    + TimberProdRatios: Like Harvest, there may be more than one entry for TimberProdRatios.  The original worksheet is TimberProdRatios.  Like EndUseRatios, a random value associated with a range of years will alter some, but not all, Timber Product Ratio values.  See the discussion of the "Sum-To-One Constraint" in Section \@ref(model-mc-samphwp).    
    
    + PrimaryProdRatios.  This type of parameter is altered much the same as TimberProdRatios and the original values may be found in the worksheet PrimaryProdRatios.  It too is subject to the "Sum-To-One Constraint".    
    
* Paper: As described above for DiscardedDispositionRatios and other parameters, some parameters represent paper (1) or wood (0) for their associated parameters.  

* First Year, Last Year: These are values that users must change.  The values in this column represent the first year of a given year period.  For instance, if our data set included harvest from 1906 to 2017 but we wanted to increase the precision of the Monte Carlo values in steps leading to the final year, then we need to indicate what years each level of precision refers to.  If only one level of precision is used, provide the first year of harvest (e.g., 1906) under the First Year column and the last year of harvest (2017) to the Last Year column. If there are three Harvest rows, we want the First Year to capture all beginning years for given year periods and Last Year to capture the terminal year.  For the first Harvest we might have First and Last Year values of 1906 and 1945, then in the second row the values 1946 and 1979, and finally the third row would contain a First Year of 1980 to 2017.   Crucially: the very first First Year must be the first year of your harvest values, whether for Harvest, TimberProdRatios, or PrimaryProdRatios.  There must not be overlap in years (e.g., if the first row had 1906 to 1945 and the next row had 1941 to 1955, the sets would overlap).  There must not be gaps (e.g., 1906 to 1945, then 1947 to 1955, leaving out 1946).  You do not have to have the same sets of years used among parameter types (e.g., Harvest year sets do not need to match TimberProdRatios year sets).  You do not need parameter types to have the same number of sets (Harvest could have two rows, PrimaryProdRatios could have three). You may have more or fewer than three year-sets per parameter type.   

* MinCI, Peak Value, MaxCI: As described above, these values are used to define the triangular distributions from which the random Monte Carlo values will be generated.  For these three columns, Peak Values should all be 1.0, with the MinCI and MaxCI symmetric around this value (the Monte Carlo code assumes symmetric triangular distributions).  That is, the MinCI and MaxCI must differ from the Peak Value by the same amount (e.g., MinCI = 0.85, Max CI = 1.15.  Both are 0.15 distant from 1.0).  The MinCI and MaxCI are the user-specified confidence intervals; e.g., the user states what they wish the confidence intervals should be around 1.0.    

* CI: This value allows the user to change what sort of a confidence interval is used. The default value is a 90% confidence interval, as was used in @stockmann2012.  The user could change this value to 0.95, or a 95% confidence interval.  This sort of adjustment will affect the spread of the triangular distribution, with a 90% confidence interval having a wider spread. 

## The quality assurance step  {#own-qa}

The Quality Assurance (QA) step is mandatory for data brought into the Shiny application and optional for the stand-alone program (see above: QA_TEST = TRUE/FALSE).   The QA code, QA_Code_Shiny.r, assesses the imported Excel file data.  The QA step has over 55 checks it performs on the incoming data to help ensure that the program will run correctly.  As it runs through its checks, it populates the file Error_Report.csv in the QA folder with results.  It first verifies that it can load a worksheet and then conducts subsequent tests on it.  The code performs tasks such as verifying that column labels are correct and that years and TPR/PPR/EUR categories match among files.  If it finds an error, it will record a "1" in the Terminate column that matches the issue at hand and describe the problem in the Comments column.  If no problem is found the Comments column will indicate which checks it made and found correct.  A zero in the Comments column may be ignored.  If an error is found, the R session will terminate (stand-alone model) or an error message will be produced preventing further analysis (Shiny application). This is on purpose!  It prevents the code from attempting to proceed.  If termination occurs, check the error report to find out which worksheet was triggering the error and why.  Below we describe the attributes that are checked for each worksheet:

All 10 worksheets: The QA code verifies that each worksheet correctly loaded.  A misspelling of the worksheet name will trigger a terminal error.  
Havest_BF:   

* The first and last column names must be \"Year\" and \"Total\".    
* Values are numeric.  
* The sum of ownership amounts must equal the sum of the total amounts.  These values can deviate from one another if a user saves the CSV file from an Excel file.  The decimal places may be lost with numbers rounded.  This rounding may cause ownership values to no longer sum to the Total amount.  Slight adjustments to the Total amount or an ownership category amount will be necessary to correct.   

BFCF:   

*	The first three column names must be \"Conversion\", \"StartYear\", and \"EndYear\".    
*	The final year value under Years must equal the last year value of Harvest_BF.  
*	Values are numeric.  

TimberProdRatios:  

*	The number of TPR years equals the number of harvest years in Harvest_BF.   
*	The year columns must be transformable to numeric values.  E.g., a text value of \"1952\" can become the integer 1952. A year column name such as \"X1952\" cannot be transformed into an integer, at least not with the code provided.   
*	The first column name must be \"TimberProductID\".  
*	The year columns must sum to 1.0.  
*	Table values are numeric.  

PrimaryProdRatios:  

*	The number of PPR years equals the number of harvest years in Harvest_BF.  
*	The year columns must be transformable to numeric values.    
*	The first column name must be \"PrimaryProductID\".  
*	The year columns must sum to the number of Timber Product Ratios, the number of rows in TimberProductRatios.  
*	Table values are numeric.  

CCF_MT_Conversion:   

*	The two columns must be named \"PrimaryProductID\" and \"CCFtoMTconv\".  
*	The listed number of Primary Products matches the number in the file PrimaryProdRatios.  
*	Table values are numeric.   

EndUseRatios:  

*	The number of years for which there are End Use Ratios must match the number of harvest years.  
*	The year columns must be transformable to numeric values.    
*	The first column name must be \"EndUseID\".  
*	The year columns must sum to the number of Primary Product Ratios, the number of rows in PrimaryProdRatios.   
*	Table values are numeric.   

RatioCategories:   

*	The column names must be, in order, \"TimberProductID\", \"PrimaryProductID\", \"EndUseID\", \"TimberProduct\", \"PrimaryProduct\", \"EndUseProduct\".  
*	The word \"fuel\" must appear in some rows of column \"EndUseProduct\".  
*	The word \"pulp\" must appear in some rows of column \"EndUseProduct\".  
*	The number of Timber Product IDs must match the number in TimberProdRatios.  
*	The number of Primary Product IDs must match the number in PrimaryProdRatios.  
*	The number of End Use IDs must match the number in EndUseRatios.  

EU_halflives:  

*	The column names must be, in order, \"EndUseID\" and \"EU_HalfLife\".  
*	The number of EndUseID row numbers equals the number of rows in EndUseRatios.  
*	Table values are numeric.  

DiscardFates:  

*	The first two columns must be named \"DiscardType\" and \"DiscardDestination\".  
*	There must be the same number of years as in Harvest_BF.    
*	The year column labels must be transformable to numeric values.  
*	Year column values must be numeric and sum to 2.0.    

MonteCarloDistrParameters:  

*	The column names must be, in order, \"Parameter_ID\", \"Parameter_Name\", \"Paper\", \"First_Year\", \"Last_Year\", \"MinCI\", \"Peak_Value\", \"MaxCI\", and \"CI\".   
*	The parameter names need to be labeled \"CCFtoMTC\", \"EndUse_HalfLives\", \"EndUseRatios\", \"DiscardedDispositionRatios\",  \"LandfillDecayLimits\", \"Landfill_HalfLives\", \"Dump_HalfLives\", \"Recovered_HalfLives\", \"Harvest\", \"TimberProdRatios\", and \"PrimaryProdRatios\".  Note that some row names can (and should) be duplicated as needed (see above).    
*	The values for the MinCI and MaxCI must be symmetric around 1.0.   
*	The parameters with multiple rows and First_Year/Last_Year values must have the years be in order and without overlap or gaps.   
*	The time series begins on the first year and the last year is within the final time series set.  
*	Table values aside from column Parameter_Name are numeric.   

## Uploading your data and running the model from the Shiny app  {#own-shiny}
Once the user has created their data file, they can open the Shiny app, either online or locally (see Running the Shiny App From Your Computer,  Section \@ref(run-opp-shiny)), and navigate to the tab Upload Data, under the navigation bar item Documentation and Data Upload.  The user selects their Excel file by clicking the Browse button and navigating to their file and opening it.  The Shiny app will display the name chosen to represent the data set (DATASET.NAME, see above). The user then runs the QA procedure by clicking on the button \"Run data file quality control\".  A button appears that allows the user to \"Download the QA output table\".  The user then clicks on the button \"Run HWP Model\".  If the QA test failed, an error message will appear to that effect.  We recommend that the user download the QA output table to determine where the error occurred.  If the QA test was passed, the button should instead take a moment to process the data through the model, announce in Model Status that the model run was a success, and change the selected data set under the \"Select a data set\" option in the sidebar to the user’s uploaded data name.  At this point the user can visit all figures in the Shiny application and view their data displayed in the figures.  They can also download tables summarizing the model run outputs by clicking on the now-appearing button \"Download HWP Tables\" on the right of the window.  

If the user only has Total harvest data (no ownership information) then certain figures will either not attempt to display ownership information or will provide pretty pictures instead.  Other figures will be unaffected.    

If the user wishes to run the Monte Carlo simulation, then once the HWP model has been run they click the \"Run Monte Carlo\" button.  A busy icon appears, letting the user know that the simulation is in progress.  The user is also informed of how long the simulation may take.  The Model Status box then has a message appear, \"Monte Carlo is complete!\".  At that point the user may download summary tables for the Monte Carlo.  The Monte Carlo Estimates tab under Carbon Storage and Emissions can now display the new simulation results.    

Note: If the user tried to view Monte Carlo simulation results after running the HWP model but before actually running the Monte Carlo simulation, they are presented with an image that explains that the Monte Carlo simulation data are not available.  If the user then runs the Monte Carlo simulation and returns to the Monte Carlo Estimates, the no-data image will remain until they switch to a previous data set (California or Oregon) and then back to their own data set.  At that time their Monte Carlo results should appear.  This feature may be improved in the future.

## Using the Stand-alone to run the HWP model and Monte Carlo simulation on your data  {#own-sa}
See the section \"The Stand-alone model: benefits, utility, and how to operate\" (Section \@ref(run-opp-sa)). 

## Generated Tables        {#own-tables}
Whether using the web version of the Shiny application, the downloaded version, or the downloaded stand-alone model, the user can obtain the same sets of output tables from the HWP model and the Monte Carlo simulation.  Previous sections describe how to download or save the tables.  This section describes the tables and their contents.  

T1.0.Annual_Harvest.csv: This table provides harvest amounts by ownership + Total if ownership data are available, and just Total if not.  The data are provided as annual input amounts or as cumulative sums.  Finally, the harvest volume is provided in the following metrics: BBF, TgC, and TgCO$_2$e.  These data should allow users to generate the Annual Timber Harvest figure from the application.   

T2.0.Harvest_Halflives.csv: This table should allow the user to create the Shiny application figure Utilized Timber Halflives.  For all years it provides the amount or proportion (pct) of harvested timber destined for fates with different half-lives.  Results are given in TgC, TgCO$_2$e, and as a proportion (pct) of the total.  Fuel has no half-life as it is burned immediately.  Short, Medium, and Long have half-lives of 1-6 years, 7 – 30 years, and 31 or more years, respectively.   

T3.0.Cumulative.Ownership.Storage.Emissions.csv: If the user data does not contain ownership information then this table is empty.  Otherwise, this table can be used to generate the figure Carbon Storage by Ownership from the Shiny application.  The table provides cumulative values for each ownership in TgC.  Columns are generated for EEC (\"\_eec\_\"), EWOEC (\"\_ewoec\_\"), PIU (\"\_pu\_\"), and SWDS (\"\_swds\_\").  The figure does not use the emissions categories, but they are provided for the user’s interest.    

T3.5.Cumulative.Ownership.Storage.Emissions.csv: If the user data does not contain ownership information then this table is empty.  This table provides the same information as T3.0 but in TgCO$_2$e instead of TgC.    

T4.0.CumulativeStorageEmissions_summary.csv: This table provides the cumulative amount of carbon stored in PIU and SWDS pools as well as the cumulative amount of carbon emitted as EEC or EWOEC.  The units are TgC and TgCO$_2$e.  These data can be used to reconstruct the Shiny application figure Carbon Storage and Emissions: Summary pool and emissions categories.    

T4.5.CumulativeStorageEmissions_summary.csv: This table provides a detailed version of T4.0, again with cumulative values in TgC and TgCO$_2$e.  It breaks out the overall PIU into PIU and Recovered, SWDS into a non-decaying portion of the landfill (Landfill_fixed), a decaying portion of the landfill (Landfill_available), and dumps.  For emissions we have burned without energy capture (Fuelwood), emissions from dumps, landfills, and recovered products (DumpsEmit, LandfillEmit, RecoveredEmit), compost, and burned waste with and without energy capture (BurnEnergyCapture, BurnNoCapture).  These data can be used to reconstruct the Shiny application figure Carbon Storage and Emissions: Pool and emission category components.   

T4.8.CumulativeStorageEmissions_halflives.csv:  These data can be used to reconstruct the Shiny application figure Carbon Storage and Emissions: Pools and emissions by halflife category.  Aside from the year column, columns in this table depict the amount of carbon (TgC, TgCO$_2$e) that resides in pools or has been cumulatively emitted from sources with different halflives.  SWDS (swds), PIU (pu), and EWOEC (E) are broken into their halflife category components, short, medium, and long (st, md, lng).  Since EEC (eec) represents fuel wood that was burned immediately, it has no halflife components.    

T5.0.AnnualStorageEmissionsChange.csv:  These data can be used to reconstruct the Shiny application figure Annual Net Change in Carbon Storage.  Values are in TgC and TgCO$_2$e.  We subtracted the value of one year’s SWDS, PIU, EWOEC, and EEC values from the previous to determine what the annual change was.  NetStockChange is the sum of the stock, or pool, values of SWDS and PIU.  The figure for \"IPCC production approach – stock change\" relies on SWDSchange, PIUchange, and NetStockChange values.  The figure \"IPCC simple decay approach = net balance\" relies on the columns Harvest/Harvest_CO2, EECchange, EWOECchange, and NetStockChange.  NetStockChange is the same line as appeared in the \"IPCC production approach – stock change\" figure.  The column Harvest is in TgC and Harvest_CO2 is in TgCO$_2$e.  The value given for harvest is the amount of harvest the year prior to the one listed under column Year.  The harvest column also equals the sum of the changes in SWDS, PIU, EWOEC, and EEC.     

MC_ComponentsSummary.csv: This table provides the information necessary to produce the figure Monte Carlo Estimates: Cumulative carbon in individual storage and emissions pools.  There are values for each year and pool/emission type (Column: Type.M) such as eec (Emitted with Energy Capture), ewoec (Emitted Without Energy Capture), swdsC (Solid Waste Disposal Sites) and pu (Products in Use).  The figure is constructed using Means (yellow line), lci, and uci (lower and upper 90% confidence intervals).  The Means are calculated by finding the mean value for an emission or pool type among iteration values for a given year.  The columns lci and uci represent lower and upper 90% confidence intervals, derived directly from the distribution of iteration values for the pool or emissions type from a given years.  The two columns pct_lci and pct_uci represent a percentage of the mean for the lower and upper confidence intervals.  Pct_lci = lci / Means; pct_uci = uci / Means.  The values in this table are cumulative MTC; the Shiny application transforms them to TgC and TgCO$_2$e.    

MC_PIU_Plus_SWDS.csv: This table provides the information necessary to produce the figure Monte Carlo Estimates: Cumulative carbon in storage pools combined (Products in Use + SWDS).  The values units are cumulative MTC which the Shiny application transforms to TgC and TgCO$_2$e.  The column Mean represents the mean value of SWDS plus PIU values for a given year across iterations.  The columns lci and uci represent lower and upper 90% confidence intervals, derived directly from the distribution of iteration values for given years.    

MC_All.xlsx: This file is only produced by the stand-alone code if the user sets Run.MC = TRUE and MC.ARRAY.OUT = TRUE.  The file has four worksheets: eec, ewoec, swdsC, and pu, representing EEC, EWOEC, SWDS, and PIU.  Each column is an iteration while each row is a year.  The data are in MTC.  The figure \"Monte Carlo Estimates: Monte Carlo convergence evaluation\" is created using the last year (last row) of the swdsC and pu worksheets.  The \"mean\" value is the successive means of the SWDS + PIU iteration values summed, starting with only the first column and adding columns to consideration (represented by the Iterations axis at the bottom of the figure).  The se, ci05, and ci95 columns are the estimated standard error and empirical 5% and 95% confidence intervals based on the number of iterations being considered.  If the user specifies 2000 iterations over 100 years of harvest data the resulting Excel file can be tens of megabytes in size.  

## What to know about running the Monte Carlo simulation   {#own-mc}
As described above, there are several controls in the worksheet HWP_MODEL_OPTIONS.  The user can set the number of iterations they would like the Monte Carlo simulation to run, and set the burn-in period length.  The burn-in period is the number of initial iterations that are not considered when calculating means and confidence intervals.  You can also set the parameters R and OPT.START if you wish.   

If you would like to see the Monte Carlo array, which includes all estimates from all iterations, you will need to run the stand-alone version of the model and set MC.ARRAY.OUT to TRUE.   

If you are trying to get the model to run or are playing around with data loading and execution on the Shiny App or stand-alone, I recommend setting the number of iterations to something small like 100.  You may find that the Monte Carlo estimates really aren’t that far off of from the standard deterministic HWP model run.  A small number of iterations will prevent you from waiting for several minutes while the simulation runs.  Running the simulations for 1000 iterations may demonstrate a reasonable burn-in number to enter into the input Excel file.  When you are ready to obtain a \"final\" estimate you can increase the number of iterations to 1500, 2000, or more.    

If you have ratio values that are close to boundaries (e.g., 0.03 and 0.98), you may notice that confidence intervals do not appear symmetrical around your mean estimate.  Please see the Section \@ref(model-mc-res).  The Monte Carlo simulation is encountering a \"sum-to-one\" boundary constraint that is frequently forcing one ratio value to its boundary (e.g., 1.0) and subsequently setting all related ratios to their opposite boundaries (e.g., 0.0).  This can result in a less continuous range of outputs, affecting the distribution of results.    



