# Version Changes   {#vc}

## Version 1.1.1: Minor Changes         {#vc-v1-1-1}

*Version 1.1.1 released 9 April 2025*

**Minor changes in Version 1.1.1**

Table download button: Users who want to download the tables behind the plotted HWP outputs for Oregon and California base datasets can do so.  The **Upload Data** tab now has a permanent button that enables download of the active HWP data set's output tables.  The "Download _______ HWP Tables" button will name which data set is currently loaded. If a user loads a new dataset and it passes the QA check and the model is run, the name of that data set will appear on the button.    

Monte Carlo fix: Previously, if users uploaded their own data and performed a Monte Carlo analysis of those data, they would not immediately see the results of the Monte Carlo when they navigated to the **Monte Carlo Estimates** tab.  They would need to switch data sets (e.g., select "California" and then re-select their data set) while at the **Monte Carlo Estimates** tab, after which the proper figures would appear.  This has now been fixed.  The Shiny reactivity timing has been updated, and after running the Monte Carlo users should immediately see their own data plotted in the **Monte Carlo Estimates** tab.  

**Carbon Storage by Ownership**: They y-axis of this plot now adjusts to the selected input, matching the behavior of the figures in the Carbon Storage and Emissions tab.


## Version 1.1.0: Major and Minor Changes         {#vc-v1-1-0}

*Version 1.1.0 released 5 May 2024*

**Major changes in Version 1.1.0**

Version 1.1.0 allows users to more easily change the displayed Monte Carlo confidence intervals.  To change the confidence intervals, a new column, MC.CI.REPORT, has been added to the HWP_TOOL_OPTIONS worksheet for all templates and provided data sets (See Section \@ref(own-prov-input-options)).  Of note, users do not change the confidence intervals by altering the "MinCI", "MaxCI" or "CI" values of the MonteCarloValues worksheet (See Sections \@ref(own-prov-input-mc), \@ref(model-mc-spec), and \@ref(model-mc-samp)); instead, these values change the dimensions of the triangular distributions from which the Monte Carlo draws values.  What these changes mean for the user:    

* Users who upload data to the app (or use the stand-alone version) need to update their input Excel files or download new template files.  The fix is easy: add the MC.CI.REPORT column to the first worksheet with your desired Monte Carlo confidence interval.  

* The QA procedure will check for the column MC.CI.REPORT and its accompanying value (Section \@ref(own-qa)).  

* The user has control over the confidence intervals generated by the Monte Carlo.

* The labels for figures produced for the App tab "Monte Carlo Estimates" should now reflect the user-stated confidence interval.


**Minor changes in Version 1.1.0**

Table 3.0 produced by the stand-alone code did not appear to incorporate a year shift like Tables 4.x and 5.  Therefore, the HWP_Tables_Code.R has been altered so that Table 3.0 populates the Years column with the harvest year + 1 to match the others.   

Carbon Storage and Emissions figures: 

* These have been altered such that the emissions data are not reported as negative values.  This change has now been made to all three of the Carbon Storage and Emissions figures.  I also removed the widget that labeled the positive values as “Storage” and negative as. “Emissions”.

* The “Pool and emission category component” figure – I reversed the SWDS and PIU colors to better match the color scheme for the "Summary pool and emissions categories" figure. 

All figures associated with the tabs "Annual Timber Harvest", "Harvest by Functional Lifespan", "Carbon Storage and Emissions", and "Annual Net Change in Carbon" were altered to accommodate longer time series, helping to prevent the overlap of X-axis year values.  This was done by increasing the X-axis increments as a function of total time steps (e.g., a 20-year increment could replace a 10-year increment). The x-axis year labels for the Monte Carlo Estimates tab figure "Cumulative carbon in individual storage and emissions pools" are now at a 45-degree angle to reduce the possibility of overlap between adjacent facet labels.  

Annual Net Change in Carbon tab, figure "IPCC production approach - stock change": The colors for PIU and SWDS were reversed to better match those of the figure “Pool and emission category component” in the Carbon Storage and Emissions tab.  

Some verbiage has been added to the Carbon Storage and Emissions tab.    

Empty space to the right of figures has been reduced. 

California's default data has been updated, and now the timber harvest data spans 1906 - 2021.  The original data set now resides in the folder `HWP Data\ModelExploration\` and is named `CA_Inputs_1952_2019.xlsx`.   




